#version: '3.9'

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    container_name: application
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=dev_db
      - DB_USER=ashish
      - DB_PASS=ashish
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: database
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=ashish
      - POSTGRES_PASSWORD=ashish

volumes:
  dev-db-data:
  dev-static-data: